### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by OlliL** [OlliL/moneyjinn-client#12]
currently unlike in the existing PHP client which support different languages, german is hardcoded in our templates

https://kazupon.github.io/vue-i18n/introduction.html

# TODO
- [x] components/InputDate.vue
- [x] month names
- [x] components/Modal.vue
- [x] components/capitalsource/CreateCapitalsourceModal.vue
- [x] components/capitalsource/DeleteCapitalsourceModal.vue
- [x] components/capitalsource/ListCapitalsourceRow.vue
- [x] components/capitalsource/SelectCapitalsource.vue
- [x] components/comparedata/CompareDataResultGroup.vue
- [x] components/comparedata/CompareDataResultRow.vue
- [x] components/contractpartner/CreateContractpartnerModal.vue
- [x] components/contractpartner/DeleteContractpartnerModal.vue
- [x] components/contractpartner/ListContractpartnerRow.vue
- [x] components/contractpartner/SelectContractpartner.vue
- [x] components/contractpartneraccount/CreateContractpartnerAccountModal.vue
- [x] components/contractpartneraccount/DeleteContractpartnerAccountModal.vue
- [x] components/contractpartneraccount/ListContractpartnerAccountRow.vue
- [x] components/contractpartneraccount/ListContractpartnerAccountsModal.vue
- [x] components/etf/CreateEtfFlowModal.vue
- [x] components/etf/DeleteEtfFlowModal.vue
- [x] components/etf/ListEtfDepotRow.vue
- [x] components/group/CreateGroupModal.vue
- [x] components/group/DeleteGroupModal.vue
- [x] components/group/ListGroupRow.vue
- [x] components/moneyflow/DeleteMoneyflowModal.vue
- [x] components/moneyflow/EditMoneyflowBase.vue
- [x] components/moneyflow/EditMoneyflowBaseSplitEntryRow.vue
- [x] components/moneyflow/EditMoneyflowModal.vue
- [x] components/moneyflow/ImportReceiptSearchRow.vue
- [x] components/moneyflow/ImportReceiptsRow.vue
- [x] components/moneyflow/SearchMoneyflowResultGroup.vue
- [x] components/moneyflow/SearchMoneyflowResultRow.vue
- [x] components/monthlysettlement/DeleteMonthlySettlementModal.vue
- [x] components/monthlysettlement/EditMonthlySettlementModal.vue
- [x] components/monthlysettlement/ShowMonthlySettlement.vue
- [x] components/postingaccount/CreatePostingAccountModal.vue
- [x] components/postingaccount/DeletePostingAccountModal.vue
- [x] components/postingaccount/ListPostingAccountRow.vue
- [x] components/postingaccount/SelectPostingAccount.vue
- [x] components/predefmoneyflow/CreatePreDefMoneyflowModal.vue
- [x] components/predefmoneyflow/DeletePreDefMoneyflowModal.vue
- [x] components/predefmoneyflow/ListPreDefMoneyflowRow.vue
- [x] components/reports/CapitalsourceTable.vue
- [x] components/reports/CapitalsourceTableRow.vue
- [x] components/reports/EtfTable.vue
- [x] components/reports/EtfTableRow.vue
- [x] components/reports/ReceiptModal.vue
- [x] components/reports/ReportTable.vue
- [x] components/reports/ReportTableRow.vue
- [x] components/user/CreateUserModal.vue
- [x] components/user/DeleteUserModal.vue
- [x] components/user/ListUserRow.vue
- [x] views/AppHome.vue
- [x] views/AppNavigation.vue
- [x] views/LoginView.vue
- [x] views/capitalsource/ListCapitalsources.vue
- [x] views/comparedata/CompareData.vue
- [x] views/contractpartner/ListContractpartners.vue
- [x] views/etf/ListEtfDepot.vue
- [x] views/group/ListGroups.vue
- [x] views/moneyflow/CreateMoneyflow.vue
- [x] views/moneyflow/ImportMoneyflows.vue
- [x] views/moneyflow/SearchMoneyflows.vue
- [x] views/monthlysettlement/ListMonthlySettlements.vue
- [x] views/postingaccount/ListPostingAccounts.vue
- [x] views/predefmoneyflow/ListPreDefMoneyflows.vue
- [x] views/receipt/ImportReceipts.vue
- [x] views/reports/ListReports.vue
- [x] views/reports/ShowReporting.vue
- [x] views/reports/ShowTrends.vue
- [x] views/user/ChangePassword.vue
- [x] views/user/ListUsers.vue
- [ ] tools/views/ThrowError.ts
