### ISSUE TITLE
rework error handling

### ISSUE THREAD

**Issue by OlliL** [OlliL/moneyjinn-client#31]
This is the corresponding issue for OlliL/moneyjinn-server#43

# Concept
- Server errors will no longer return with HTTP status 200
- The frontend must now handle HTTP status codes 400, 422 explicitly and all other outside the 200 range in a general way

# What to do
- modify the axios response interceptor to handle the different HTTP status code
- create a BackendError class to help handling the different backend errors 
- create a BackendErrorType enum to reflect the different error types 
  - Generic Client Error (400)
  - Authentication Error (403)
  - Validation Error (422)
  - all other Errors
- create a handleBackendError function every components catch() block can just call to populate their serverErrors DIV
- modify every Handler calling component and introduce a catch block which handles the possible backend errors.

# TODO List
- [X] components/capitalsource/CreateCapitalsourceModal.vue
- [X] components/capitalsource/DeleteCapitalsourceModal.vue
- [x] components/contractpartner/CreateContractpartnerModal.vue
- [x] components/contractpartner/DeleteContractpartnerModal.vue
- [x] components/contractpartneraccount/CreateContractpartnerAccountModal.vue
- [x] components/contractpartneraccount/DeleteContractpartnerAccountModal.vue
- [x] components/contractpartneraccount/ListContractpartnerAccountsModal.vue
- [x] components/etf/CreateEtfFlowModal.vue
- [x] components/etf/DeleteEtfFlowModal.vue
- [x] components/group/CreateGroupModal.vue
- [x] components/group/DeleteGroupModal.vue
- [x] components/moneyflow/DeleteMoneyflowModal.vue
- [x] components/moneyflow/EditMoneyflowBase.vue
- [x] components/moneyflow/EditMoneyflowModal.vue
- [x] components/moneyflow/ImportReceiptsRow.vue
- [x] components/monthlysettlement/DeleteMonthlySettlementModal.vue
- [x] components/monthlysettlement/EditMonthlySettlementModal.vue
- [x] components/monthlysettlement/ShowMonthlySettlement.vue
- [x] components/postingaccount/CreatePostingAccountModal.vue
- [x] components/postingaccount/DeletePostingAccountModal.vue
- [x] components/predefmoneyflow/CreatePreDefMoneyflowModal.vue
- [x] components/predefmoneyflow/DeletePreDefMoneyflowModal.vue
- [x] components/reports/EtfTable.vue
- [x] components/reports/ReceiptModal.vue
- [x] components/reports/ReportTable.vue
- [x] components/user/CreateUserModal.vue
- [x] components/user/DeleteUserModal.vue
- [x] handler/CapitalsourceControllerHandler.ts
- [x] handler/CompareDataControllerHandler.ts
- [x] handler/ContractpartnerAccountControllerHandler.ts
- [x] handler/ContractpartnerControllerHandler.ts
- [x] handler/EtfControllerHandler.ts
- [x] handler/EventControllerHandler.ts
- [x] handler/GroupControllerHandler.ts
- [x] handler/ImportedMoneyflowControllerHandler.ts
- [x] handler/ImportedMoneyflowReceiptControllerHandler.ts
- [x] handler/MoneyflowControllerHandler.ts
- [x] handler/MoneyflowReceiptControllerHandler.ts
- [x] handler/MonthlySettlementControllerHandler.ts
- [x] handler/PostingAccountControllerHandler.ts
- [x] handler/PreDefMoneyflowControllerHandler.ts
- [x] handler/ReportControllerHandler.ts
- [x] handler/UserControllerHandler.ts
- [ ] stores/CapitalsourceStore.ts
- [ ] stores/ContractpartnerStore.ts
- [ ] stores/PostingAccountStore.ts
- [x] views/AppHome.vue
- [X] views/LoginView.vue
- [x] views/comparedata/CompareData.vue
- [x] views/etf/ListEtfDepot.vue
- [x] views/group/ListGroups.vue
- [x] views/moneyflow/CreateMoneyflow.vue
- [x] views/moneyflow/ImportMoneyflows.vue
- [x] views/moneyflow/SearchMoneyflows.vue
- [x] views/monthlysettlement/ListMonthlySettlements.vue
- [x] views/predefmoneyflow/ListPreDefMoneyflows.vue
- [x] views/receipt/ImportReceipts.vue
- [x] views/reports/ListReports.vue
- [x] views/reports/ShowReporting.vue
- [x] views/reports/ShowTrends.vue
- [x] views/user/ChangePassword.vue
- [x] views/user/ListUsers.vue
